"""games に thumb_key を追加

Revision ID: 948d50d4765e
Revises: b7c4870a7aa4
Create Date: 2025-09-15 07:25:10.508627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '948d50d4765e'
down_revision = 'b7c4870a7aa4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('thumb_key', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'thumb_key')
    # ### end Alembic commands ###

