"""games に cover_key と reviews.user_id を追加

Revision ID: b7c4870a7aa4
Revises: c351e79c1176
Create Date: 2025-09-15 06:43:06.014634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7c4870a7aa4'
down_revision = 'c351e79c1176'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('cover_key', sa.String(length=512), nullable=True))
    op.add_column('reviews', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_reviews_user_id'), 'reviews', ['user_id'], unique=False)
    op.create_foreign_key(None, 'reviews', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_index(op.f('ix_reviews_user_id'), table_name='reviews')
    op.drop_column('reviews', 'user_id')
    op.drop_column('games', 'cover_key')
    # ### end Alembic commands ###

