"""add unique constraint games title+platform

Revision ID: c351e79c1176
Revises: 
Create Date: 2025-09-15 05:53:58.068352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c351e79c1176'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_games_title_platform', 'games', ['title', 'platform'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_games_title_platform', 'games', type_='unique')
    # ### end Alembic commands ###

