# docker-compose.yml（修正例）
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  backend:
    build:
      context: ./apps/backend
      dockerfile: ../../docker/backend.Dockerfile
    env_file:
      - .env.backend
    depends_on:
      - db
      - minio
    ports:
      - "4000:4000"
    volumes:
      - ./apps/backend:/app
    command: sh -c "npm run dev"

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: ../../docker/frontend.Dockerfile
    env_file:
      - .env.frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./apps/frontend:/app
    command: sh -c "npm run dev -- --host"

volumes:
  db_data:
  minio_data: